name: Index Docker images
description: Create a package SBOM for Docker images using Atomist
author: docker
branding:
  icon: anchor
  color: blue

inputs:
  image:
    description: "Image"
    required: true
  api-key:
    description: "API key"
    required: true
  workspace:
    description: "Workspace ID"
    required: true
runs:
  using: docker
  image: docker://ghcr.io/cdupuis/index-cli-plugin@sha256:decca66afb36f86e1b65956e6f3e8da5ce120f000ddcd397610c7e7a23f24de2
  env:
    ATOMIST_API_KEY: ${{ inputs.api-key }}
    ATOMIST_WORKSPACE: ${{ inputs.workspace }}
  args:
    - index
    - upload
    - --image
    - ${{ inputs.image }}
